### PR TITLE
Site update

### PR DESCRIPTION
**Pull request by v0dro**

### CODE REVIEW

**Comment by v0dro** [comment]
@mohawkjohn can you approve and merge this in the master branch?

**Comment by v0dro** [comment]
Also can you remove this review requirement on the master branch? There are not supposed to be _any_ user commits on the master anyway. Everything should happen in source which octopress then automatically copies to master.

**Comment by v0dro** [comment]
I had to make this PR simply because the master had many user commits previously and its not possble to push to master directly.

**Comment by mohawkjohn** [comment]
Yes, review requirement has been removed.

**Pull request merged**
