### PR TITLE
Add All-in-one interactive plotting using daru-view post

### PR DESCRIPTION
**Pull request by Prakriti-nith**
This highlights my proposal and main topics that I'll be covering in my talk at ParisRB conf 2020.

### CODE REVIEW

**Comment by Prakriti-nith** [comment]
This PR is in progress. I will update the details of each topic soon.

**Comment by prasunanand** [comment]
Closed for no activity.

@Prakriti-nith If you want to get the blog in, modify the PR.

**Comment by pjotrp** [comment]
@Prakriti-nith I think you should submit this - it is very important for future members of SciRuby and participation in GSoC. We are all grateful for the program! If you can expand a little on the context - add two paragraphs and some pointers to your code I think we should be able to accept.

**Comment by pjotrp** [comment]
If you have the slides and/or links to the talk that would be great too!

**Pull request closed without merging**
