### PR TITLE
edit the blog after review

### PR DESCRIPTION
**Pull request by prasunanand**

### CODE REVIEW

**Comment by mohawkjohn** [comment]
I think I realized I never pushed my version. Sorry. It's up now. Don't know how I missed that.

**Comment by mohawkjohn** [comment]
@prasunanand Please squash. It makes it much easier to review.

**Comment by prasunanand** [comment]
@mohawkjohn Please review.

**Comment by pjotrp** [comment]
lgtm

**Comment by agisga** [comment]
Great article!

@prasunanand The name of the mixed models gem is technically spelled with an underscore (like this: mixed_models). In the blog post you spell it a few times with a dash or a space instead. You might want to change that (unless you have a good reason not to).

**Comment by prasunanand** [comment]
Thanks @agisga 

I have corrected the spelling.

**Comment by mohawkjohn** [comment]
Merged as https://github.com/SciRuby/sciruby.com/commit/cdeec364ae4b65e35701e60a33c16b148ed33469

**Pull request closed without merging**
