### PR TITLE
Upgrading to latest octopress

### PR DESCRIPTION
**Pull request by v0dro**

### CODE REVIEW

**Comment by mohawkjohn** [comment]
Can you please provide a justification?

**Comment by mohawkjohn** [comment]
Also, I think this merge needs to be into master, not source. source is only for site-specific stuff.

**Comment by v0dro** [comment]
Its the latest code from the Octopress master branch. It has better rake tasks, improved style code, bug fixes etc. I ran the update procedure described here: http://octopress.org/docs/updating/

It should be in source. The bugfixes will be automatically carried over to master when you run `rake generate`, which I think should be done only by the site maintainer. That's how octo press works. Changes to source -> rake generate -> Changes carried over to master.

**Comment by v0dro** [comment]
I'd like to add that octopress works well when NOT A SINGLE user change is made to the master branch. It all should be in source and simply calling `rake generate` will perpetrate the necessary changes.

**Comment by mohawkjohn** [comment]
It may be that our Octopress is not configured the same way as other sites you've looked at, but this is not how it works for Sciruby.com.

master: original Octopress code
source: SciRuby-specific changes to the code
rake generate/deploy: generates the site and deploys it to a separate repository

I'm going to pull in @audy here to make sure I have it right.

**Comment by v0dro** [comment]
If I'm getting this right, the master branch contains the stuff that is used by Github to generate the Jekyll blog.

That's the reason why  you can write your posts in markdown in the `source` branch and then have them converted to HTML that end up in the master branch.

It's probably not being done the right way if you've been modifying the master branch yourself. All changes are supposed to happen in source. Thats hows its designed.

**Comment by audy** [comment]
> It's probably not being done the right way if you've been modifying the master branch yourself. All changes are supposed to happen in source. Thats hows its designed. - @v0dro 

I think you're right. Traveling right now. I can take a closer look next week.

**Comment by v0dro** [comment]
GSOC students need to update their blog posts so if this could be done at the earliest that would be great.

**Comment by audy** [comment]
@v0dro is there anything preventing you and your students from updating blog posts with the current version of Octopress?

**Comment by v0dro** [comment]
No. But I just think it would be much better if everyone could commit to the updated blog.

**Comment by mohawkjohn** [comment]
@v0dro: @audy is right. Let's not put the cart before the horse. Please
submit a pull request for your blog entry on the source branch and we'll
work on the upgrade in the future.

**Comment by v0dro** [comment]
OK.

**Pull request closed without merging**
